<div class="container">
    <?php
        $form->prepare();
   echo $this->form()->openTag($form);
    ?>

    <h2 class="form-signin-heading">Login</h2>
    <label for="inputEmail" class="sr-only">Email:</label>
    <?php echo $this->formEmail($form->get('email')); ?>
    <label for="inputPassword" class="sr-only">Senha:</label>
    <?php echo $this->formPassword($form->get('password')); ?>
    <div class="checkbox">
        <label>
            <input type="checkbox" value="remember-me"> Lembrar senha
        </label>
    </div>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Entrar</button>

    <?php echo $this->form()->closeTag(); ?>
</div> <!-- /container -->