<?php
$title = 'Cadastro de Funcionário';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<?php
// This provides a default CSS class and placeholder text for the title element:
$nome = $form->get('nome');


$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('funcionario', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>

<div class="form-group">
    <?= $this->formLabel($nome) ?>
    <?= $this->formElement($nome) ?>
    <?= $this->formElementErrors()->render($nome, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
?>
<!--
<h2><span class="glyphicon glyphicon-user"></span> Cadastro de Funcionário</h2>

<form  method="post">
    <hr>
    <h3>Dados Pessoas</h3>
    <div class="row">
        <div class="form-group col-md-6">
            <label for="nome">Nome:</label>
            <input type="text" class="form-control" id="nome">
        </div>

        <div class="form-group col-md-3">
            <label for="rg">RG:</label>
            <input type="text" class="form-control" id="rg" placeholder="99.999.999-X">
        </div>

        <div class="form-group col-md-3">
            <label for="cpf">CPF:</label>
            <input type="text" class="form-control" id="cpf" placeholder="999.999.999.99">
        </div>
        <div class="form-group col-md-4">
            <label for="dataNasc">Data Nasc.:</label>
            <input type="date" class="form-control" id="dataNasc">
        </div>

        <div class="form-group col-md-4">
            <label for="estadoCivil">Estado Civil:</label>
            <select id="estadoCivil" class="form-control">
                <option>Solteiro(a)</option>
                <option>Casado(a)</option>
                <option>Divorciado(a)</option>
                <option>Viúvo(a)</option>
            </select>
        </div>

        <div class="form-group col-md-4">
            <label for="sexo">Sexo:</label>
            <div class="radio">
                <label class="radio-inline"><input type="radio" name="sexo" checked>Fem.</label>
                <label class="radio-inline"><input type="radio" name="sexo">Masc.</label>
            </div>

        </div>
        <div class="form-group col-md-4">
            <label for="email">E-mail:</label>
            <input type="email" class="form-control" id="email">
        </div>
        <div class="form-group col-md-4">
            <label for="telefoneFixo">Telefone Fixo:</label>
            <input type="text" class="form-control" id="telefoneFixo">
        </div>
        <div class="form-group col-md-4">
            <label for="telefoneMovel">Telefone Movel:</label>
            <input type="text" class="form-control" id="telefoneMovel">
        </div>
    </div>
    <hr>
    <h3>Endereço</h3>
    <div class="row">
        <div class="form-group col-md-2">
            <label for="cep">CEP:</label>
            <input type="text" class="form-control" id="cep" placeholder="99999-999">
        </div>

        <div class="form-group col-md-6">
            <label for="logradouro">Logradouro:</label>
            <input type="text" class="form-control" id="logradouro" placeholder="Rua/Av.">
        </div>

        <div class="form-group col-md-1">
            <label for="numero">Número:</label>
            <input type="text" class="form-control" id="numero">
        </div>
        <div class="form-group col-md-3">
            <label for="bairro">Bairro:</label>
            <input type="text" class="form-control" id="bairro">
        </div>
        <div class="form-group col-md-4">
            <label for="complemento">Complemento:</label>
            <input type="text" class="form-control" id="complemento">
        </div>

        <div class="form-group col-md-4">
            <label for="cidade">Cidade:</label>
            <input type="text" class="form-control" id="cidade">
        </div>

        <div class="form-group col-md-4">
            <label for="estado">Estado:</label>
            <input type="text" class="form-control" id="estado">
        </div>
    </div>
    <hr>
    <h3>Dados Contratuais</h3>
    <div class="row">
        <div class="form-group col-md-6">
            <label for="departamento">Departamento:</label>
            <input type="text" class="form-control" id="departamento">
        </div>
        <div class="form-group col-md-6">
            <label for="funcao">Função:</label>
            <input type="text" class="form-control" id="funcao">
        </div>

        <div class="form-group col-md-6">
            <label for="salario">Salário:</label>
            <input type="text" class="form-control" id="salario" placeholder="R$ 9.999,99">
        </div>
        <div class="form-group col-md-3">
            <label for="admissao">Data de Admissão:</label>
            <input type="date" class="form-control" id="admissao">
        </div>
        <div class="form-group col-md-3">
            <label for="demissao">Data de Demissão:</label>
            <input type="date" class="form-control" id="demissao">
        </div>
    </div>
    <hr>
    <div class="row">
        <button class="btn btn-primary col-md-2">Salvar</button>

    </div>

</form>


<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.0/jquery.mask.js"></script>
<script>
    $(document).ready(function () {
        var $seuCampoCpf = $("#cpf");
        var $seuCampoRg = $("#rg");
        var $seuCampoCep = $("#cep");
        $seuCampoCpf.mask('000.000.000-00', {reverse: false});
        $seuCampoRg.mask('00.000.000-A', {reverse: false});
        $seuCampoCep.mask('00000-000', {reverse: false});
    });

    $(document).ready(function() {

        function limpa_formulário_cep() {
            // Limpa valores do formulário de cep.
            $("#logradouro").val("");
            $("#bairro").val("");
            $("#cidade").val("");
            $("#estado").val("");
        }

        //Quando o campo cep perde o foco.
        $("#cep").blur(function() {

            //Nova variável "cep" somente com dígitos.
            var cep = $(this).val().replace(/\D/g, '');

            //Verifica se campo cep possui valor informado.
            if (cep != "") {

                //Expressão regular para validar o CEP.
                var validacep = /^[0-9]{8}$/;

                //Valida o formato do CEP.
                if(validacep.test(cep)) {

                    //Preenche os campos com "..." enquanto consulta webservice.
                    $("#rua").val("...");
                    $("#bairro").val("...");
                    $("#cidade").val("...");
                    $("#uf").val("...");
                    $("#ibge").val("...");

                    //Consulta o webservice viacep.com.br/
                    $.getJSON("https://viacep.com.br/ws/"+ cep +"/json/?callback=?", function(dados) {

                        if (!("erro" in dados)) {
                            //Atualiza os campos com os valores da consulta.
                            $("#logradouro").val(dados.logradouro);
                            $("#bairro").val(dados.bairro);
                            $("#cidade").val(dados.localidade);
                            $("#estado").val(dados.uf);
                        } //end if.
                        else {
                            //CEP pesquisado não foi encontrado.
                            limpa_formulário_cep();
                            alert("CEP não encontrado.");
                        }
                    });
                } //end if.
                else {
                    //cep é inválido.
                    limpa_formulário_cep();
                    alert("Formato de CEP inválido.");
                }
            } //end if.
            else {
                //cep sem valor, limpa formulário.
                limpa_formulário_cep();
            }
        });
    });

</script>
</script>
-->