<?php
$title = 'Cadastro de Funcionário';
$this->headTitle($title);
?>
<h1><span class="glyphicon glyphicon-user"></span> <?= $this->escapeHtml($title) ?></h1>

<?php
// This provides a default CSS class and placeholder text for the title element:
$nome = $form->get('nome');
$rg = $form->get('rg');
$cpf = $form->get('cpf');
$dataNasc = $form->get('dataNasc');
$estadoCivil = $form->get('estadoCivil');
$sexo = $form->get('sexo');

$email = $form->get('email');
$telefoneFixo = $form->get('telefoneFixo');
$telefoneMovel = $form->get('telefoneMovel');

$cep = $form->get('cep');
$logradouro = $form->get('logradouro');
$numero = $form->get('numero');
$bairro = $form->get('bairro');
$complemento = $form->get('complemento');
$cidade = $form->get('cidade');
$estado = $form->get('estado');

$salario = $form->get('salario');
$funcao = $form->get('funcao');
$departamento = $form->get('departamento');

$dataAdmissao = $form->get('dataAdmissao');
$dataDemissao = $form->get('dataDemissao');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('funcionario', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<hr>
<h3>Dados Pessoas</h3>
<div class="row">
    <div class="form-group col-md-6">
        <?= $this->formLabel($nome) ?>
        <?= $this->formElement($nome) ?>
        <?= $this->formElementErrors()->render($nome, ['class' => 'text-danger']) ?>
    </div>
    <div class="form-group col-md-3">
        <?= $this->formLabel($rg) ?>
        <?= $this->formElement($rg) ?>
        <?= $this->formElementErrors()->render($rg, ['class' => 'text-danger']) ?>
    </div>
    <div class="form-group col-md-3">
        <?= $this->formLabel($cpf) ?>
        <?= $this->formElement($cpf) ?>
        <?= $this->formElementErrors()->render($cpf, ['class' => 'text-danger']) ?>
    </div>
    <div class="form-group col-md-4">
        <?= $this->formLabel($dataNasc) ?>
        <?= $this->formElement($dataNasc) ?>
        <?= $this->formElementErrors()->render($dataNasc, ['class' => 'text-danger']) ?>
    </div>
    <div class="form-group col-md-4">
        <?= $this->formLabel($estadoCivil) ?>
        <?= $this->formElement($estadoCivil) ?>
        <?= $this->formElementErrors()->render($estadoCivil, ['class' => 'text-danger']) ?>
    </div>
    <div class="form-group col-md-4">
        <?= $this->formLabel($sexo) ?>
        <div class="radio">
            <?= $this->formElement($sexo) ?>
         </div>
        <?= $this->formElementErrors()->render($sexo, ['class' => 'text-danger']) ?>
    </div>

    <div class="form-group col-md-4">
        <?= $this->formLabel($email) ?>
        <?= $this->formElement($email) ?>
        <?= $this->formElementErrors()->render($email, ['class' => 'text-danger']) ?>
    </div>

    <div class="form-group col-md-4">
        <?= $this->formLabel($telefoneFixo) ?>
        <?= $this->formElement($telefoneFixo) ?>
        <?= $this->formElementErrors()->render($telefoneFixo, ['class' => 'text-danger']) ?>
    </div>
    <div class="form-group col-md-4">
        <?= $this->formLabel($telefoneMovel) ?>
        <?= $this->formElement($telefoneMovel) ?>
        <?= $this->formElementErrors()->render($telefoneMovel, ['class' => 'text-danger']) ?>
    </div>
</div>
<hr>
<h3>Endereço</h3>
<div class="row">
    <div class="form-group col-md-2">
        <?= $this->formLabel($cep) ?>
        <?= $this->formElement($cep) ?>
        <?= $this->formElementErrors()->render($cep, ['class' => 'text-danger']) ?>
    </div>

    <div class="form-group col-md-6">
        <?= $this->formLabel($logradouro) ?>
        <?= $this->formElement($logradouro) ?>
        <?= $this->formElementErrors()->render($logradouro, ['class' => 'text-danger']) ?>
    </div>

    <div class="form-group col-md-1">
        <?= $this->formLabel($numero) ?>
        <?= $this->formElement($numero) ?>
        <?= $this->formElementErrors()->render($numero, ['class' => 'text-danger']) ?>
    </div>
    <div class="form-group col-md-3">
        <?= $this->formLabel($bairro) ?>
        <?= $this->formElement($bairro) ?>
        <?= $this->formElementErrors()->render($bairro, ['class' => 'text-danger']) ?>
    </div>
    <div class="form-group col-md-4">
        <?= $this->formLabel($complemento) ?>
        <?= $this->formElement($complemento) ?>
        <?= $this->formElementErrors()->render($complemento, ['class' => 'text-danger']) ?>
    </div>
    <div class="form-group col-md-4">
        <?= $this->formLabel($cidade) ?>
        <?= $this->formElement($cidade) ?>
        <?= $this->formElementErrors()->render($cidade, ['class' => 'text-danger']) ?>
    </div>
    <div class="form-group col-md-4">
        <?= $this->formLabel($estado) ?>
        <?= $this->formElement($estado) ?>
        <?= $this->formElementErrors()->render($estado, ['class' => 'text-danger']) ?>
    </div>
</div>
<hr>
<h3>Dados Contratuais</h3>
<div class="row">
    <div class="form-group col-md-4">
        <?= $this->formLabel($funcao) ?>
        <?= $this->formElement($funcao) ?>
        <?= $this->formElementErrors()->render($funcao, ['class' => 'text-danger']) ?>
    </div>
    <div class="form-group col-md-4">
        <?= $this->formLabel($departamento) ?>
        <?= $this->formElement($departamento) ?>
        <?= $this->formElementErrors()->render($departamento, ['class' => 'text-danger']) ?>
    </div>
    <div class="form-group col-md-4">
        <?= $this->formLabel($salario) ?>
        <?= $this->formElement($salario) ?>
        <?= $this->formElementErrors()->render($salario, ['class' => 'text-danger']) ?>
    </div>
    <div class="form-group col-md-4">
        <?= $this->formLabel($dataAdmissao) ?>
        <?= $this->formElement($dataAdmissao) ?>
        <?= $this->formElementErrors()->render($dataAdmissao, ['class' => 'text-danger']) ?>
    </div>
    <div class="form-group col-md-4">
        <?= $this->formLabel($dataDemissao) ?>
        <?= $this->formElement($dataDemissao) ?>
        <?= $this->formElementErrors()->render($dataDemissao, ['class' => 'text-danger']) ?>
    </div>
</div>
<hr>
<div class="row">
<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
?>
</div>


<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.0/jquery.mask.js"></script>

<script>
    $(document).ready(function () {
        $("#cpf").mask('000.000.000-00', {reverse: false});
        $("#rg").mask('00.000.000-A', {reverse: false});
        $("#telefoneFixo").mask('(000) 0000-0000');
        $("#telefoneMovel").mask('(000) 00000-0000');
        $("#cep").mask('00000-000', {reverse: false});
        $("#salario").mask('#.##0,00', {reverse: true});
    });



    $(document).ready(function() {

        function limpa_formulário_cep() {
            // Limpa valores do formulário de cep.
            $("#logradouro").val("");
            $("#bairro").val("");
            $("#cidade").val("");
            $("#estado").val("");
        }

        //Quando o campo cep perde o foco.
        $("#cep").blur(function() {

            //Nova variável "cep" somente com dígitos.
            var cep = $(this).val().replace(/\D/g, '');

            //Verifica se campo cep possui valor informado.
            if (cep != "") {

                //Expressão regular para validar o CEP.
                var validacep = /^[0-9]{8}$/;

                //Valida o formato do CEP.
                if(validacep.test(cep)) {

                    //Preenche os campos com "..." enquanto consulta webservice.
                    $("#rua").val("...");
                    $("#bairro").val("...");
                    $("#cidade").val("...");
                    $("#uf").val("...");
                    $("#ibge").val("...");

                    //Consulta o webservice viacep.com.br/
                    $.getJSON("https://viacep.com.br/ws/"+ cep +"/json/?callback=?", function(dados) {

                        if (!("erro" in dados)) {
                            //Atualiza os campos com os valores da consulta.
                            $("#logradouro").val(dados.logradouro);
                            $("#bairro").val(dados.bairro);
                            $("#cidade").val(dados.localidade);
                            $("#estado").val(dados.uf);
                        } //end if.
                        else {
                            //CEP pesquisado não foi encontrado.
                            limpa_formulário_cep();
                            alert("CEP não encontrado.");
                        }
                    });
                } //end if.
                else {
                    //cep é inválido.
                    limpa_formulário_cep();
                    alert("Formato de CEP inválido.");
                }
            } //end if.
            else {
                //cep sem valor, limpa formulário.
                limpa_formulário_cep();
            }
        });
    });

</script>
</script>