<?php

$title = 'Deletetar Funcionario';
$url   = $this->url('funcionario', ['action' => 'delete', 'id' => $id]);

$this->headTitle($title);

?>

<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Deseja excluir o(a) Funcionário(a)
    "<?= $this->escapeHtml($funcionario->getNome()) ?>"?
</p>

<form action="<?= $url ?>" method="post">
    <div class="form-group">
        <input type="hidden" name="id" value="<?= (int) $funcionario->getId() ?>" />
        <input type="submit" class="btn btn-danger" name="del" value="Sim" />
        <input type="submit" class="btn btn-success" name="del" value="Não" />
    </div>
</form>