<div id="top" class="row">
    <div class="col-md-3">
        <h2>Funcionários</h2>
    </div>

    <div class="col-md-6">

    </div>

    <div class="col-md-3">
        <a href="<?= $this->url('funcionario', ['action' => 'add']) ?>" class="btn btn-primary pull-right h2">Novo Item</a>
    </div>
</div>


<table class="table table-striped table-hover">
    <thead>
    <tr>
        <th>#id</th>
        <th>Nome</th>
        <th>Função</th>
        <th>Departamento</th>
        <th>Visualizar</th>
        <th>Editar</th>
        <th>Excluir</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($funcionarios as $funcionario):?>
        <?php extract($funcionario->getArrayCopy());?>
        <tr>
            <td><?=$funcionario->getId()?></td>
            <td><?=$funcionario->getNome()?></td>

            <td>
                <?php foreach ($funcoes as $funcao){
                    if($funcao->getId()==$funcionario->getIdFuncao()){
                        echo $funcao->getDescricao();
                    }
                }  ?>
            </td>

            <td>
                <?php foreach ($departamentos as $departamento){
                    if($departamento->getId()==$funcionario->getIdDepartamento()){
                        echo $departamento->getDescricao();
                    }
                }  ?>
            </td>
            <td><a class="text-warning" href="<?= $this->url('funcionario', ['action' => 'detail', 'id' => $funcionario->getId()]) ?>"><span class="glyphicon glyphicon-search"></span></a></td>
            <td><a class="text-success" href="<?= $this->url('funcionario', ['action' => 'edit', 'id' => $funcionario->getId()]) ?>"><span class="glyphicon glyphicon-pencil"></span></a></td>
            <td><a class="text-danger" href="<?= $this->url('funcionario', ['action' => 'delete', 'id' => $funcionario->getId()]) ?>"><span class="glyphicon glyphicon-trash"></span></a></td>
            </tr>
    <?php endforeach;?>
    </tbody>
</table>